DROP TABLE IF EXISTS `feeds`;
CREATE TABLE `feeds` (
	`id` INT(11) PRIMARY KEY AUTO_INCREMENT NOT NULL,
	`type` VARCHAR(256) NULL DEFAULT NULL,
	`timestamp` INT(11) NOT NULL DEFAULT CURRENT_TIME(),
	`audio_url`  VARCHAR(2000) NULL DEFAULT  NULL,
	`video_urls` TEXT NULL DEFAULT '',
	`title` VARCHAR(2000) NOT NULL DEFAULT 'Senza Titolo',
	`text_content` TEXT NULL DEFAULT NULL,
	`author` VARCHAR(500) NULL DEFAULT NULL
);

DROP TABLE IF EXISTS `banner_images`;
CREATE TABLE `banner_images` (
	`id` INT(11) PRIMARY KEY AUTO_INCREMENT NOT NULL,
	`image_url` VARCHAR(256) NULL DEFAULT NULL
);